import os

import dotenv

dotenv.load_dotenv(override=True)

KAKAO_REST_API_KEY = os.getenv("KAKAO_REST_API_KEY", "")

NAVER_CLIENT_ID = os.getenv("NAVER_CLIENT_ID", "")
NAVER_CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET", "")

GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH", "")

TWITTER_API_KEY = os.getenv("TWITTER_API_KEY", "")
TWITTER_API_KEY_SECRET = os.getenv("TWITTER_API_KEY_SECRET", "")
TWITTER_ACCESS_TOKEN = os.getenv("TWITTER_ACCESS_TOKEN", "")
TWITTER_ACCESS_TOKEN_SECRET = os.getenv("TWITTER_ACCESS_TOKEN_SECRET", "")
TWITTER_BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN", "")

LANGSMITH_API_KEY = os.getenv("LANGSMITH_API_KEY", "")

LOGS_DIR = os.getenv("LOGS_DIR")